import Head from "next/head";
import { Header, Navbar } from "../components";

export default function Home() {
  return (
    <div className="fixed flex h-screen w-screen flex-col bg-black">
      <Head>
        <title>Alexey's portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex flex-grow">
        <Navbar />
      </main>
    </div>
  );
}
