import Head from "next/head";
import Link from "next/link";

import { Montserrat } from "@next/font/google";

const inter = Montserrat({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Alexey's portfolio | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative flex flex-grow select-none bg-[#151515] pl-8 font-mono">
        <div className="absolute inset-0 z-0 flex flex-col items-start justify-center whitespace-nowrap pl-8 text-[140px] font-black leading-[1.1] text-gray-600/30">
          <div className="-mt-20">
            <h1 className={inter.className}>
              Alexey !! <br /> Website
            </h1>
          </div>
        </div>
        <div className="z-20 flex flex-col items-start justify-center">
          <h1 className="-mt-12 text-4xl text-white">Alexey Poltoradnev</h1>
          <div className="typewriter mt-4 text-3xl text-gray-300">
            <h2>Web Enthusiast</h2>
          </div>
          <div className="mt-12 flex items-center space-x-4">
            <Link
              href="/projects"
              className="border border-gray-300 py-2 px-4 text-white transition duration-300 ease-out hover:border-gray-400 hover:text-gray-400 active:scale-95"
            >
              View Work
            </Link>
            <Link
              href="/contact"
              className="border border-gray-300 py-2 px-4 text-white transition duration-300 ease-out hover:border-gray-400 hover:text-gray-400 active:scale-95"
            >
              Reach Me
            </Link>
          </div>
        </div>
      </div>
    </>
  );
}
