import Head from "next/head";

export default function Projects() {
  return (
    <>
      <Head>
        <title>Alexey's portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex-grow bg-[#151515]">Projects</div>
    </>
  );
}
